spring.application.name=ApiGateway
server.port=8081
#eureka 
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
#to connect of service to api
spring.cloud.gateway.routes[0].id=AuthenticationService
spring.cloud.gateway.routes[0].uri=lb://AUTHENTICATIONSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=AdminService
spring.cloud.gateway.routes[1].uri=lb://ADMINSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/department/**,/medical/**

spring.cloud.gateway.routes[2].id=CustomerService
spring.cloud.gateway.routes[2].uri= lb://CUSTOMERSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/appointment/**