spring.application.name=AdminService
spring.datasource.url=jdbc:mysql://localhost:3306/appointmentmanagementsystem
spring.datasource.username=root
spring.datasource.password=Mithi@6963#
spring.jpa.hibernate.ddl-auto=update
server.port=8082